name: Build Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Build Release
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Make Aria2c Executable
        if: matrix.os != 'windows-latest'
        run: |
          chmod -R 777 ./static/engine/

      - name: Build Electron App
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          release: ${{ startsWith(github.ref, 'refs/tags') }}
          github_token: ${{ secrets.github_token }}
